apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongo-pv
  labels:
    type: local
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
  {{- if .Values.persistence.hostPath }}
  hostPath:
    path: {{ .Values.persistence.dir }}
  {{- end }}